### ISSUE TITLE
readability of postgres data folder

### ISSUE THREAD

**Issue by rezad1393** [bitmagnet-io/bitmagnet#114]
**Have you checked the roadmap on the website, and existing issues, before opening a dupllcate issue?**
Yes

**Is your feature request related to a problem? Please describe.**
I want to be able to run this as regular user and access the database (I have added my user to docker group).
when I run this as docker, the postgres data folder gets its permission set as userid=70 and group root.
I can change the owner and mod of data folder but at the next run the postgres folder gets userid of 70 again and its permission gets reset to only user drwx------

**Describe the solution you'd like**
I want to be able to access the db it is creates, which a better way would be the database to be created the user owned.

**Describe alternatives you've considered**
changing the permission after every run.
not really elegant.

.

**Comment by mgdigital** [comment]
Hi, I don't think I've understood the problem being caused by the file permissions but it would be best to refer to the Postgres and/or Docker documentation to resolve this.

The app can be configured to point at any Postgres instance. If you're using the example docker-compose file the database will be exposed on port 5432 and you can connect using the credentials provided in the environment variables (by default user `postgres`/password `postgres`).
