### ISSUE TITLE
Add clickhouse support

### ISSUE THREAD

**Issue by Ghost-chu** [bitmagnet-io/bitmagnet#298]
- [x] I have checked the existing issues to avoid duplicates
- [x] I have redacted any info hashes and content metadata from any logs or screenshots attached to this issue

### Is your feature request related to a problem? Please describe

Bitmagnet is using PgSQL, which is good, but not good enough.
However, when the amount of data is quite large, Bitmagnet can consume a significant amount of disk space.

Solution: Use a database that supports transparent compression. clickhouse is a good choice. Clickhouse is a good choice. It is very fast in the face of very large data volumes, and supports a wide variety of compression methods such as zstd. It can also efficiently retrieve and store all kinds of data. It also supports SQL statements.

In particular, Clickhouse is also particularly fond of inserting large amounts of data in large batches. It's perfect for the Bitmagnet crawling around scenario.

### Describe the solution you'd like

It would be great if Bitmagnet could add Clickhouse support!

### Describe alternatives you've considered

If Clickhouse could add MongoDB, that would be a good candidate as well. But I think Clickhouse is mainstream enough and fits the scenario quite well.

### Additional context

No, have a good day and thank you for hard work & time :)

**Comment by mgdigital** [comment]
> when the amount of data is quite large, Bitmagnet can consume a significant amount of disk space

This seems self-evident and not a solveable problem; marginal improvements can be made for sure, but also storage is inexpensive. 

Adding support for _[insert any database engine other than Postgres]_ would be a huge undertaking so is unlikely to happen without a very compelling case being made for it. I'm afraid I've never heard of Clickhouse. Postgres is the de-facto open source database and is good enough for most tasks. 

You are of course free to implement something that would ingest into any data source you like from Bitmagnet's DB. If someone can make a PoC using a different engine that's clearly superior for the use cases we require, then this can be reviewed.

**Comment by leofidus** [comment]
I have spent some time investigating this a bit. My initial impression is that the potential space savings are substantial.

My total database size in postgres (as counted by `pg_total_relation_size`) is 195GB. After a `VACUUM FULL` that dropped down to 164GB. To keep things simple, let's ignore indexes for a moment. Without indexes the postgres database takes 78GB (as counted by `pg_table_size`). 99% of that is used by four tables (torrent_files, torrent_contents, torrents, torrents_torrent_sources), so I'll ignore the other tables for now, leaving us with **77GB**.

I then set up a clickhouse instance, set the default compression to zstd, and for each of the four tables ran a version of

```sql
CREATE TABLE bitmagnet.<table_name>
ENGINE = MergeTree
Order By (<reasonable primary key>,<other columns that might improve sorting or compression>) AS
SELECT * FROM postgresql('<ip>:<port>', 'bitmagnet', '<table_name>', '<username>', '<passwort>')
```

The result, as reported by 

```
SELECT
    `table`,
    formatReadableSize(sum(data_compressed_bytes)) AS compressed_size,
    formatReadableSize(sum(data_uncompressed_bytes)) AS uncompressed_size
FROM system.parts
WHERE (database = 'bitmagnet') AND active
GROUP BY `table`
```

was a database that's just **13.6GB** big (compressed size). That's a substantial improvement over postgresql's 77GB. And that's likely understating the improvement, since sorting the content allows us to save space on primary key indexes. For example in postgres my torrent_files table is 60GB, but has a 44GB primary key index (on infohash, path). In clickhouse I sorted the table by those keys, which basically removes the need for that 44GB index.

There are some potential downsides:

- Bitmagnet does a lot of inserts and updates, I haven't tested how well clickhouse deals with that. Imho the amount of data written in total is a bigger issue with bitmagnet than the data stored, and clickhouse might not help much there
- Bitmagnet heavily uses transactions. Clickhouse's transaction support is pretty limited

There is potential to reduce the storage requirements by 5-10x, but it wouldn't be without challenges. I'll investigate a bit more as I find time

**Comment by mgdigital** [comment]
This would involve a complete rewrite of the persistence layer and so it's just very unlikely to happen. Since this issue was raised I've seen Clickhouse mentioned in a few places so it's clearly gaining momentum but has nothing like the maturity or community of Postgres. There must be a trade-off in the size saving, whether it's performance or consistency. Lack of transactions would likely make it even more of a non-starter, Also storage cost for a full fat Bitmagnet DB on SSD is modest so I don't really see saving space as a huge win. I'm happy to have my mind changed on this sort of thing (though I feel there's a mountain to climb in this case) and/or for someone to build a standalone integration into Clickhouse.

**Comment by leofidus** [comment]
I agree that the current storage requirements aren't that bad. Using less space would be nice, but my main qualm with the current persistence layer is how it burns through the TBW of my SSD.

To add to the challenges column, Bitmagnet seems to use a lot of `on conflict update`. Clickhouse has a complicated relationship with updating rows, so that would at a minimum require changing some query logic, in addition to the database package. It's certainly not a small or quick change.

I'll keep working on it a bit. Though even if it ever becomes mature enough for a pull request I'm not sure how that'd end. It might just come down to how the difference in query and insert performance looks like
