### ISSUE TITLE
Redis DB configuration is not respected

### ISSUE THREAD

**Issue by munissor** [bitmagnet-io/bitmagnet#38]
**Have you checked the roadmap on the website, and existing issues, before opening a dupllcate issue?**
Yes

**Describe the bug**
Looks like regardless of the redis.db setting, values are written to db:0

**To Reproduce**

- Set the REDIS_DB env variable to a value different than 0
- start bitmagnet
- from the container, verify that `bitmagnet config show` displays the env value for the `redis.db` setting
- listing the keys for the configured db, returns no keys
- listing keys from the db:0 shows some bitmagnet keys

**Expected behavior**
Redis are written on the specified db only

**General (please complete the following information):**

- Bitmagnet version: 0.0.7
- OS and version: Arch linux - Docker

**Comment by mgdigital** [comment]
This one had me confused but I've found the issue now. This bug will affect any config key where the struct key cannot be converted with `strcase.ToSnake` then back to the same value with `strcase.ToCamel` (in this case, `DB`).

We need to start comparing with the original struct key instead of doing `strcase.ToCamel` here: https://github.com/bitmagnet-io/bitmagnet/blob/main/internal/boilerplate/config/config.go#L171
