### ISSUE TITLE
crawling given info hashes

### ISSUE THREAD

**Issue by rcl-viveksharma** [bitmagnet-io/bitmagnet#57]
is their a way i can configure it to crawl only given hash info:
Use case:

I can just input info hashes from dumps.
i can get info hashes from rss feeds or other source.

so after importing only hashes i want to be able to crawl about these hashes and update these entries with file name and seeders leechers etc.

this way after sharing info hash and name dumps this software could be used to classify and fill info like file name etc

**Comment by mgdigital** [comment]
The crawler is only capable of finding things by chance rather than locating specific things. The only option right now is to use the import endpoint, but you'll need a bit more info than just the hash, i.e. name and size (which you might well have if you're doing it from a RSS source): https://bitmagnet.io/tutorials/importing.html

At some point I was thinking of integrating https://itorrents.org/, so you could input a hash and it would get it if it's cached on there - bear in mind that is heavily rate limited though...
